// AUTH
export const AUTH_START = "AUTH START";
export const AUTH_SUCCESS = "AUTH SUCCESS";
export const AUTH_FAILED = "AUTH FAILED";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const TOGGLE_AUTH = "TOGGLE AUTH";


//CUSTOMER
export const GET_CUSTOMERS = "GET CUSTOMERS";
export const GET_CUSTOMERS_SUCCESS = "GET CUSTOMERS SUCCESS";
export const GET_SINGLE_CUSTOMER_SUCCESS = "GET SINGLE CUSTOMER SUCCESS";
export const ADD_CUSTOMER_INIT = "ADD CUSTOMER INIT";
export const ADD_CUSTOMER = "ADD CUSTOMER";
export const ADD_CUSTOMER_SUCCESS = "ADD CUSTOMER SUCCESS";
export const DELETE_CUSTOMER_INIT = "DELETE CUSTOMER INIT";
export const DELETE_CUSTOMER_SUCCESS = "DELETE CUSTOMER SUCCESS";

export const EDIT_CUSTOMER_INIT = "EDIT CUSTOMER INIT";
export const EDIT_CUSTOMER_DONE = "EDIT CUSTOMER DONE";
export const EDIT_CUSTOMER_SUCCESS = "EDIT CUSTOMER SUCCESS";

export const LOADING = "LOADING";
export const ERROR_OCCURED = "ERROR_OCCURED";

//staff
export const GET_STAFF = "GET STAFF";
export const GET_STAFF_SUCCESS = "GET STAFF SUCCESS";
export const GET_SINGLE_STAFF_SUCCESS = "GET SINGLE STAFF SUCCESS";

export const ADD_STAFF_INIT = "ADD STAFF INIT";
export const ADD_STAFF = "ADD STAFF";
export const ADD_STAFF_SUCCESS = "ADD STAFF SUCCESS";

export const DELETE_STAFF_INIT = "DELETE STAFF INIT";
export const DELETE_STAFF_SUCCESS = "DELETE STAFF SUCCESS";

export const EDIT_STAFF_DONE = "EDIT STAFF DONE";
export const EDIT_STAFF_INIT = "EDIT STAFF INIT";
export const EDIT_STAFF_SUCCESS = "EDIT STAFF SUCCESS";

//savings product
export const GET_SAVINGS_PRODUCT = "GET SAVINGS PRODUCT";
export const GET_SAVINGS_PRODUCT_SUCCESS = "GET SAVINGS PRODUCT SUCCESS";
export const GET_SINGLE_SAVINGS_SUCCESS = "GET SINGLE SAVINGS PRODUCT SUCCESS";
export const ADD_SAVINGS_PRODUCT_INIT = "ADD SAVINGS PRODUCT INIT";
export const ADD_SAVINGS_PRODUCT = "ADD SAVINGS PRODUCT";
export const ADD_SAVINGS_PRODUCT_SUCCESS = "ADD SAVINGS PRODUCT SUCCESS";
export const DELETE_SAVINGS_PRODUCT_INIT = "DELETE SAVINGS PRODUCT INIT";
export const DELETE_SAVINGS_PRODUCT_SUCCESS = "DELETE SAVINGS PRODUCT SUCCESS";

export const EDIT_SAVINGS_PRODUCT_INIT = "EDIT SAVINGS PRODUCT INIT";
export const EDIT_SAVINGS_PRODUCT_DONE = "EDIT SAVINGS PRODUCT DONE";
export const EDIT_SAVINGS_PRODUCT_SUCCESS = "EDIT SAVINGS PRODUCT SUCCESS";